name: Run Jupyter Notebooks

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  find-notebooks:
    runs-on: ubuntu-latest
    outputs:
      notebook-list: ${{ steps.get-notebooks.outputs.notebooks-list }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jq papermill

      - name: Get all notebooks
        id: get-notebooks
        run: |
          {
          NOTEBOOKS=$(find ./for-research -name '*.ipynb' -print0 | jq -Rsc 'split("\u0000")[:-1]')
          if [ -z "$NOTEBOOKS" ]; then
            echo "No notebooks found"
            NOTEBOOKS="[]"
          fi
          echo "notebooks=$NOTEBOOKS" >> $GITHUB_ENV
          cat $GITHUB_ENV
          echo "Got all notebooks!"
          }
      - name: Get all notebooks
        run: echo ${{ env.notebooks }}

  test-goddamn-env:
    needs: find-notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Get all notebooks
        run: |
          echo ${{ needs.find-notebooks.env.notebooks }}
          echo "got-em"

  run-notebooks:
    needs: find-notebooks
    runs-on: ubuntu-latest
    if: ${{ needs.find-notebooks.env.notebooks != '[]' }}
    strategy:
      matrix:
        notebook: ${{ needs.find-notebooks.env.notebooks }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill

      - name: Run notebook with Papermill
        run: |
          papermill ${{ matrix.notebook }} /dev/null
