name: Run Jupyter Notebooks

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  find-notebooks:
    runs-on: ubuntu-latest
    outputs:
      notebook-list: ${{ steps.get-notebooks.outputs.notebooks }}
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jq papermill

      - name: Get all notebooks
        id: get-notebooks
        run: |
          {
          NOTEBOOKS=$(find . -name '*.ipynb' | jq -R -s 'split("\n")[:-1]')
          if [ -z "$NOTEBOOKS" ]; then
            echo "No notebooks found"
            NOTEBOOKS="[]"
          fi
          echo "notebook-list=$NOTEBOOKS<<EOF" >> $GITHUB_OUTPUT
          }

  run-notebooks:
    needs: find-notebooks
    runs-on: ubuntu-latest
    if: ${{ needs.find-notebooks.outputs['notebook-list'] != '[]' }}
    strategy:
      matrix:
        notebook: ${{ fromJson(needs.find-notebooks.outputs['notebook-list']) }}
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill

      - name: Run notebook with Papermill
        run: |
          papermill ${{ matrix.notebook }} /dev/null
