name: Run Jupyter Notebooks

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  find-notebooks:
    runs-on: ubuntu-latest
    outputs:
      notebooks: ${{ steps.get-notebooks.outputs.notebooks }}
      NOTEBOOKS8-cpp: ${{ steps.get-notebooks.outputs.NOTEBOOKS8-cpp }}
      NOTEBOOKS8-python: ${{ steps.get-notebooks.outputs.NOTEBOOKS8-python }}
      NOTEBOOKS13-cpp: ${{ steps.get-notebooks.outputs.NOTEBOOKS13-cpp }}
      NOTEBOOKS13-python: ${{ steps.get-notebooks.outputs.NOTEBOOKS13-python }}
      NOTEBOOKS13-uproot: ${{ steps.get-notebooks.outputs.NOTEBOOKS13-uproot }}
      NOTEBOOKS13-rdataframe: ${{ steps.get-notebooks.outputs.NOTEBOOKS13-rdataframe }}
      NOTEBOOKS-research: ${{ steps.get-notebooks.outputs.NOTEBOOKS-research }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jq papermill

      - name: Get all notebooks
        id: get-notebooks
        run: |
          {
          NOTEBOOKS=$(find . -name '*.ipynb' -print0 | jq -Rsc 'split("\u0000")[:-1]')
          if [ -z "$NOTEBOOKS" ]; then
            echo "No notebooks found"
            NOTEBOOKS="[]"
          fi

          NOTEBOOKS8-cpp=$(find ./8-TeV-examples/cpp -name '*.ipynb' -print0 | jq -Rsc 'split("\u0000")[:-1]')
          if [ -z "$NOTEBOOKS8-cpp" ]; then
            echo "No notebooks found"
            NOTEBOOKS8-cpp="[]"
          fi
          echo "NOTEBOOKS8-cpp=$NOTEBOOKS8-cpp" >> $GITHUB_OUTPUT

          NOTEBOOKS8-python=$(find ./8-TeV-examples/python -name '*.ipynb' -print0 | jq -Rsc 'split("\u0000")[:-1]')
          if [ -z "$NOTEBOOKS8-python" ]; then
            echo "No notebooks found"
            NOTEBOOKS8-python="[]"
          fi
          echo "NOTEBOOKS8-python=$NOTEBOOKS8-python" >> $GITHUB_OUTPUT

          NOTEBOOKS13-cpp=$(find ./13-TeV-examples/cpp -name '*.ipynb' -print0 | jq -Rsc 'split("\u0000")[:-1]')
          if [ -z "$NOTEBOOKS13-cpp" ]; then
            echo "No notebooks found"
            NOTEBOOKS13-cpp="[]"
          fi
          echo "NOTEBOOKS13-cpp=$NOTEBOOKS13-cpp" >> $GITHUB_OUTPUT

          NOTEBOOKS13-uproot=$(find ./13-TeV-examples/uproot_python -name '*.ipynb' -print0 | jq -Rsc 'split("\u0000")[:-1]')
          if [ -z "$NOTEBOOKS13-uproot" ]; then
            echo "No notebooks found"
            NOTEBOOKS13-uproot="[]"
          fi
          echo "NOTEBOOKS13-uproot=$NOTEBOOKS13-uproot" >> $GITHUB_OUTPUT

          NOTEBOOKS13-python=$(find ./13-TeV-examples/python -name '*.ipynb' -print0 | jq -Rsc 'split("\u0000")[:-1]')
          if [ -z "$NOTEBOOKS13-python" ]; then
            echo "No notebooks found"
            NOTEBOOKS13-python="[]"
          fi
          echo "NOTEBOOKS13-python=$NOTEBOOKS13-python" >> $GITHUB_OUTPUT

          NOTEBOOKS13-rdataframe=$(find ./13-TeV-examples/rdataframe -name '*.ipynb' -print0 | jq -Rsc 'split("\u0000")[:-1]')
          if [ -z "$NOTEBOOKS13-rdataframe" ]; then
            echo "No notebooks found"
            NOTEBOOKS13-rdataframe="[]"
          fi
          echo "NOTEBOOKS13-rdataframe=$NOTEBOOKS13-rdataframe" >> $GITHUB_OUTPUT

          NOTEBOOKS-research=$(find ./13-TeV-examples/for-research -name '*.ipynb' -print0 | jq -Rsc 'split("\u0000")[:-1]')
          if [ -z "$NOTEBOOKS-research" ]; then
            echo "No notebooks found"
            NOTEBOOKS13-research="[]"
          fi
          echo "NOTEBOOKS-research=$NOTEBOOKS1research" >> $GITHUB_OUTPUT
          
          cat $GITHUB_OUTPUT
          echo "Got all notebooks!"
          }

  run-notebooks:
    needs: find-notebooks
    runs-on: ubuntu-latest
    if: ${{ needs.find-notebooks.outputs.NOTEBOOKS13-python != '[]' }}
    strategy:
      matrix:
        notebook: ${{ fromJson(needs.find-notebooks.outputs.NOTEBOOKS13-python) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill

      - name: Run notebook with Papermill
        run: |
          papermill ${{ matrix.notebook }} /dev/null
